# Generated by Django 6.1 on 2026-08-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_disable_mailing", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["full_name"],
                "permissions": [
                    (
                        "can_view_all_recipients",
                        "Может просматривать всех получателей",
                    ),
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
